// <auto-generated />
using System;
using EldorAnnualLeave.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EldorAnnualLeave.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EldorAnnualLeave.Core.Models.AnnualLeaveType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ALT_Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALT_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Eldor_AnnualLeaveType");
                });

            modelBuilder.Entity("EldorAnnualLeave.Core.Models.Calendar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnualLeaveType_ID")
                        .HasColumnType("int");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_Day")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Start_Day")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Eldor_Calendar");
                });

            modelBuilder.Entity("EldorAnnualLeave.Core.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Annual_Leave")
                        .HasColumnType("int");

                    b.Property<string>("Employee_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Employee_ID")
                        .HasColumnType("int");

                    b.Property<string>("Employee_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Last_Calculation")
                        .HasColumnType("datetime2");

                    b.Property<int>("SAP_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Eldor_Employee");
                });

            modelBuilder.Entity("EldorAnnualLeave.Core.Models.LeaveAddition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Added_Annual_Leave")
                        .HasColumnType("int");

                    b.Property<int>("AnnualLeaveType_ID")
                        .HasColumnType("int");

                    b.Property<int>("Completed_Years")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Eldor_LeaveAddition");
                });
#pragma warning restore 612, 618
        }
    }
}
